version: 1
# filename_format: '%Y-%m-%d_UTC%z'
# incremental False = replaces the existing configuration
incremental: False  
# disable_existing_loggers will be ignored if incremental is True
disable_existing_loggers: False
loggers:
  root:
    level: 'WARNING'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_path_handler']
    propagate: False
  pfeed:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
  # NOTE: avoid name conflict with pfund, add "_data" suffix to e.g. bybit
  yahoo_finance_data:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
  bybit_data:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
  databento_data:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
handlers:
  file_handler:
    class: 'logging.FileHandler'
    level: 'DEBUG'
    formatter: 'file'
  compressed_timed_rotating_file_handler:
    class: 'pfund.plogging.handlers.CompressedTimedRotatingFileHandler'
    level: 'DEBUG'
    formatter: 'file'
    kwargs: {'when': 'midnight', 'backupCount': 7, 'utc': True, 'encoding': 'utf-8'}
  stream_handler:
    class: 'logging.StreamHandler'
    level: 'INFO'
    formatter: 'console'
  stream_path_handler:
    class: 'logging.StreamHandler'
    level: 'INFO'
    formatter: 'path'
formatters:
  path:
    format: '%(asctime)s.%(msecs)03d | %(levelname)s | %(name)s | %(message)s | %(shortpath)s fn:%(funcName)s ln:%(lineno)d'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
  file:
    format: '%(asctime)s.%(msecs)03d | %(levelname)s | %(message)s | %(filename)s fn:%(funcName)s ln:%(lineno)d'
    datefmt: '%H:%M:%S%z'
  console:
    format: '%(asctime)s.%(msecs)03d | %(levelname)s | %(name)s | %(message)s | %(filename)s fn:%(funcName)s ln:%(lineno)d'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'