version: 1
# filename_format: '%Y-%m-%d_UTC%z'
# incremental False = replaces the existing configuration
incremental: False  
# disable_existing_loggers will be ignored if incremental is True
disable_existing_loggers: False
loggers:
  # NOTE: do NOT add root logger here, otherwise it will conflict with the root logger set in pfund's logging.yml
  yfinance:  # controls yfinance's logger
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
  pfeed:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
  pfeed.yahoo_finance:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
  pfeed.bybit:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
  pfeed.databento:
    level: 'DEBUG'
    handlers: ['compressed_timed_rotating_file_handler', 'stream_handler']
    propagate: False
handlers:
  compressed_timed_rotating_file_handler:
    class: 'pfund_kit.logging.handlers.CompressedTimedRotatingFileHandler'
    level: 'DEBUG'
    formatter: 'file'
    kwargs: {'when': 'midnight', 'backupCount': 7, 'utc': True, 'encoding': 'utf-8'}
    filters: ['trimmedpath']
  stream_handler:
    class: 'logging.StreamHandler'
    level: 'INFO'
    formatter: 'console'
    filters: ['trimmedpath']
formatters:
  file:
    format: '%(asctime)s.%(msecs)03d | %(levelname)s | %(name)s | %(message)s | %(trimmedpath)s fn:%(funcName)s ln:%(lineno)d'
    datefmt: '%H:%M:%S%z'
  console:
    (): pfund_kit.logging.formatters.ColoredFormatter
    format: '%(asctime)s.%(msecs)03d | %(levelname)s | %(name)s | %(message)s | %(trimmedpath)s fn:%(funcName)s ln:%(lineno)d'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
filters:
  trimmedpath:
    (): pfund_kit.logging.filters.TrimmedPathFilter
