SUPPORTED_DATA_TYPES = ['raw', 'tick', 'second', 'minute', 'hour', 'daily']
SUPPORTED_DATA_FEEDS = ['YAHOO_FINANCE', 'BYBIT']
SUPPORTED_DOWNLOAD_DATA_SOURCES = ['BYBIT']
ALIASES = {
    'YF': 'YAHOO_FINANCE',
}