from enum import StrEnum


class DataSource(StrEnum):
    YAHOO_FINANCE = 'YAHOO_FINANCE'
    FINANCIAL_MODELING_PREP = 'FINANCIAL_MODELING_PREP'
    BYBIT = 'BYBIT'
    BINANCE = 'BINANCE'
    # DATABENTO = 'DATABENTO'
